In [1]:
import pandas as pd
import psycopg2

# Database connection parameters
params = {
    "host": "localhost",       # or your server's IP address/domain name
    "port": 5433,             # default postgres port
    "database": "ipek_database",
    "user": "postgres",       # default superuser
    "password": "Arasya123."
}

# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM account"

# Load data into a pandas DataFrame
account = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame
print(account)

                  created_at                 updated_at  is_deleted  \
0 2023-07-27 04:41:04.803048 2023-08-03 08:05:36.111597       False
1 2023-07-27 04:39:57.678383 2023-08-03 08:05:41.316470       False
2 2023-07-26 18:36:12.562229 2023-08-03 08:05:33.300269       False
3 2023-07-26 18:36:12.562229 2023-08-03 08:05:33.300269       False
4 2023-07-27 04:39:57.678383 2023-08-03 08:05:41.316470       False
5 2023-08-03 11:12:14.317763 2023-08-03 11:12:14.317763       False
6 2023-07-26 18:36:12.562229 2023-08-03 08:05:33.300269       False
7 2023-07-27 04:41:04.803048 2023-08-03 08:05:36.111597       False

  deleted_at                                    id     type  \
0       None  1978c662-4cd4-4164-9d1e-0a938a89b43d  DEPOSIT
1       None  4c01f230-75ab-4cb8-b83d-8a9214795d40  DEPOSIT
2       None  5332798b-523f-4d9a-9c7d-38f5aedfad60  DEPOSIT
3       None  683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e   CREDIT
4       None  7d22926a-9632-4861-95a6-7aa2211963ae  DEPOSIT
5       None  a283b87e-d112-4ec4-b61d-e9e9150c7fbc  DEPOSIT
6       None  a55c6d9f-4651-4e95-afce-7e597390a0b6  DEPOSIT
7       None  d8a1ad91-a46d-4ba4-837c-9113962d08b9  DEPOSIT

                             subtype_id                                org_id  \
0  796ab970-42cb-4fe1-a913-7846c25335e6  c84e81e6-8663-427e-983e-95c9660da260
1  796ab970-42cb-4fe1-a913-7846c25335e6  c84e81e6-8663-427e-983e-95c9660da260
2  e3f99647-fbe3-4176-bc3c-2cef55054c1c  fe1a173a-76d6-4647-bb00-d615fb07f64c
3  854d29af-ef01-44d4-83a5-f1421d7eeeed  fe1a173a-76d6-4647-bb00-d615fb07f64c
4  7c4989df-3dd3-495e-a819-a414c4aebe15  c84e81e6-8663-427e-983e-95c9660da260
5  97d09c89-eef8-4de0-baa3-9311f2c37859  fe1a173a-76d6-4647-bb00-d615fb07f64c
6  97d09c89-eef8-4de0-baa3-9311f2c37859  fe1a173a-76d6-4647-bb00-d615fb07f64c
7  7c4989df-3dd3-495e-a819-a414c4aebe15  c84e81e6-8663-427e-983e-95c9660da260

                             external_id  balance_available_amount  \
0  Z1889jN9oysoqKbw6Ookibo8gb04PMUxEQPyM                      0.00
1  BbODwjxjkLsB5Rw74MELhMnJkNYgE5igvX9Ej                    500.57
2  8mz6rb4YJnuydDRd4zNPhP1PjEZO0mUYO6dZP                   3459.10
3  5Zg7vx0YJNULNAgN0yq3S3D34NV7bwiN7pqVL                  23500.93
4  qNgLPprpqKuLmA15wX6dH1k8xDjOALUq1MJpx                   8892.14
5  jZDJdE0qMXSE5Ev30e8osLAkd0Y08gtvee483                  42847.82
6  ZZrdkBK6yQURA6jAvg37IX7XyjDVkMF8qZ0vq                   1061.32
7  5waajMDjVJsZk9aBA1Z6ikn5akXmEwfKRLmE7                  70000.00

   balance_current_amount  limit_amount currency_id account_number_mask  \
0                    0.00           NaN         USD                6350
1                  500.57           NaN         USD                2435
2                 3459.10           NaN         USD                9836
3                   55.24       23700.0         USD                5620
4                 8892.14           NaN         USD                1567
5                42852.82           NaN         USD                3145
6                 1061.32           NaN         USD                3150
7                70000.00           NaN         USD                5287

                                   name                         official_name  \
0                       Mercury Savings                       Mercury Savings
1  BUSINESS MARKET RATE SAVINGS ...2435  BUSINESS MARKET RATE SAVINGS ...2435
2                        TOTAL CHECKING                                  None
3                           CREDIT CARD                     Ultimate Rewards®
4             BUSINESS CHECKING ...1567             BUSINESS CHECKING ...1567
5                       Savings Account                       Savings Account
6                         CHASE SAVINGS                                  None
7                      Mercury Checking                      Mercury Checking

                              source_id              financial_institution_id  \
0  7e83b1fd-9a07-4044-8212-5d981c80fd06  97807784-6743-468d-b3ce-bb3d499ad903
1  5b97073d-cb13-40e8-a040-e87f30ace849  70d7f11e-d6a1-4b00-9391-3470d3690c12
2  7965c146-d0d5-4cfb-a858-18c12cb90606  642a874e-a1c4-4256-b1b5-76b9fe407644
3  7965c146-d0d5-4cfb-a858-18c12cb90606  642a874e-a1c4-4256-b1b5-76b9fe407644
4  5b97073d-cb13-40e8-a040-e87f30ace849  70d7f11e-d6a1-4b00-9391-3470d3690c12
5  b6186ac8-7642-4c66-a3bb-0d9e05106b68  ccab6f08-1c16-487a-90c9-9715a722d03f
6  7965c146-d0d5-4cfb-a858-18c12cb90606  642a874e-a1c4-4256-b1b5-76b9fe407644
7  7e83b1fd-9a07-4044-8212-5d981c80fd06  97807784-6743-468d-b3ce-bb3d499ad903

  external_last_updated_datetime
0        2023-08-03 05:20:04.733
1        2023-08-03 04:57:25.494
2        2023-08-02 20:59:12.899
3        2023-08-02 20:59:12.899
4        2023-08-03 04:57:25.494
5        2023-08-03 11:11:56.354
6        2023-08-02 20:59:12.899
7        2023-08-03 05:20:04.733

In [7]:
account

,created_at,updated_at,is_deleted,deleted_at,id,type,subtype_id,org_id,external_id,balance_available_amount,balance_current_amount,limit_amount,currency_id,account_number_mask,name,official_name,source_id,financial_institution_id,external_last_updated_datetime
0,2023-07-27 04:41:04.803048,2023-08-03 08:05:36.111597,False,None,1978c662-4cd4-4164-9d1e-0a938a89b43d,DEPOSIT,796ab970-42cb-4fe1-a913-7846c25335e6,c84e81e6-8663-427e-983e-95c9660da260,Z1889jN9oysoqKbw6Ookibo8gb04PMUxEQPyM,0.00,0.00,NaN,USD,6350,Mercury Savings,Mercury Savings,7e83b1fd-9a07-4044-8212-5d981c80fd06,97807784-6743-468d-b3ce-bb3d499ad903,2023-08-03 05:20:04.733
1,2023-07-27 04:39:57.678383,2023-08-03 08:05:41.316470,False,None,4c01f230-75ab-4cb8-b83d-8a9214795d40,DEPOSIT,796ab970-42cb-4fe1-a913-7846c25335e6,c84e81e6-8663-427e-983e-95c9660da260,BbODwjxjkLsB5Rw74MELhMnJkNYgE5igvX9Ej,500.57,500.57,NaN,USD,2435,BUSINESS MARKET RATE SAVINGS ...2435,BUSINESS MARKET RATE SAVINGS ...2435,5b97073d-cb13-40e8-a040-e87f30ace849,70d7f11e-d6a1-4b00-9391-3470d3690c12,2023-08-03 04:57:25.494
2,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,5332798b-523f-4d9a-9c7d-38f5aedfad60,DEPOSIT,e3f99647-fbe3-4176-bc3c-2cef55054c1c,fe1a173a-76d6-4647-bb00-d615fb07f64c,8mz6rb4YJnuydDRd4zNPhP1PjEZO0mUYO6dZP,3459.10,3459.10,NaN,USD,9836,TOTAL CHECKING,None,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
3,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,CREDIT,854d29af-ef01-44d4-83a5-f1421d7eeeed,fe1a173a-76d6-4647-bb00-d615fb07f64c,5Zg7vx0YJNULNAgN0yq3S3D34NV7bwiN7pqVL,23500.93,55.24,23700.0,USD,5620,CREDIT CARD,Ultimate Rewards®,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
4,2023-07-27 04:39:57.678383,2023-08-03 08:05:41.316470,False,None,7d22926a-9632-4861-95a6-7aa2211963ae,DEPOSIT,7c4989df-3dd3-495e-a819-a414c4aebe15,c84e81e6-8663-427e-983e-95c9660da260,qNgLPprpqKuLmA15wX6dH1k8xDjOALUq1MJpx,8892.14,8892.14,NaN,USD,1567,BUSINESS CHECKING ...1567,BUSINESS CHECKING ...1567,5b97073d-cb13-40e8-a040-e87f30ace849,70d7f11e-d6a1-4b00-9391-3470d3690c12,2023-08-03 04:57:25.494
5,2023-08-03 11:12:14.317763,2023-08-03 11:12:14.317763,False,None,a283b87e-d112-4ec4-b61d-e9e9150c7fbc,DEPOSIT,97d09c89-eef8-4de0-baa3-9311f2c37859,fe1a173a-76d6-4647-bb00-d615fb07f64c,jZDJdE0qMXSE5Ev30e8osLAkd0Y08gtvee483,42847.82,42852.82,NaN,USD,3145,Savings Account,Savings Account,b6186ac8-7642-4c66-a3bb-0d9e05106b68,ccab6f08-1c16-487a-90c9-9715a722d03f,2023-08-03 11:11:56.354
6,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,a55c6d9f-4651-4e95-afce-7e597390a0b6,DEPOSIT,97d09c89-eef8-4de0-baa3-9311f2c37859,fe1a173a-76d6-4647-bb00-d615fb07f64c,ZZrdkBK6yQURA6jAvg37IX7XyjDVkMF8qZ0vq,1061.32,1061.32,NaN,USD,3150,CHASE SAVINGS,None,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
7,2023-07-27 04:41:04.803048,2023-08-03 08:05:36.111597,False,None,d8a1ad91-a46d-4ba4-837c-9113962d08b9,DEPOSIT,7c4989df-3dd3-495e-a819-a414c4aebe15,c84e81e6-8663-427e-983e-95c9660da260,5waajMDjVJsZk9aBA1Z6ikn5akXmEwfKRLmE7,70000.00,70000.00,NaN,USD,5287,Mercury Checking,Mercury Checking,7e83b1fd-9a07-4044-8212-5d981c80fd06,97807784-6743-468d-b3ce-bb3d499ad903,2023-08-03 05:20:04.733

In [2]:
# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction"

# Load data into a pandas DataFrame
transaction = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [3]:
transaction

,created_at,updated_at,is_deleted,deleted_at,id,org_id,currency_id,vendor_id,source_id,location_id,...,datetime,authorized_datetime,is_pending,payment_channel,check_number,account_id,transaction_type_id,direction,general_ledger_account_id,transaction_subtype_id
0,2023-07-26 18:36:14.550089,2023-07-26 18:36:14.550089,False,NaT,0001378f-f744-4eb0-8b7b-867135071625,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,59475fb0-772f-4400-80f2-ac0100ee3921,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-07-16 16:51:11,2023-07-15 00:00:00,False,ONLINE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,0d8eb8f2-a462-4cce-98c5-2a2a681f80d4,OUTFLOW,None,dd56c6ee-b6d7-4f86-8620-80d7561b91af
1,2023-07-26 18:36:28.244705,2023-07-26 18:36:28.244705,False,NaT,0023ef80-81d0-4928-9a9e-22a85b810433,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,d53f2785-c3d9-45d3-be66-b3bc5316af37,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-01-30 16:58:42,2023-01-28 12:34:50,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
2,2023-07-26 18:36:20.091959,2023-07-26 18:36:20.091959,False,NaT,00241232-d353-4c0e-9a8e-6db7a4f42571,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,a17ca5fb-dc1f-4c17-9e59-53e7aa4873fd,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-01-30 14:31:30,2022-01-29 22:51:51,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,6e780bfb-9c0e-4b33-a8f2-8c8f6546213e,OUTFLOW,None,6ad0082b-e775-46d3-99bf-6f64c6eed332
3,2023-07-26 18:36:28.854304,2023-07-26 18:36:28.854304,False,NaT,003ec9a6-3078-48b5-a5ab-0b4dad9348bd,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,e0303369-24a3-49fe-b741-b9bfaefdcdab,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-02-21 17:58:43,2023-02-20 14:08:21,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,6e780bfb-9c0e-4b33-a8f2-8c8f6546213e,OUTFLOW,None,1691b033-2899-43b0-a3a3-680a9adec73f
4,2023-07-26 18:36:29.413804,2023-07-26 18:36:29.413804,False,NaT,00464921-516d-4e15-b236-b049b433bf46,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,342b827a-0607-4574-9249-41ecfda8de85,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-03-24 18:05:10,2023-03-23 14:05:39,False,ONLINE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,f5bec75c-2c0a-450a-b11b-bfe412eabf23,OUTFLOW,None,1c5b2213-d653-42cd-8086-e7db3c3ca432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085,2023-07-26 18:36:21.499517,2023-07-26 18:36:21.499517,False,NaT,ffac2fe0-3fd7-4dbc-abe1-e672d983a99e,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,c724db4c-cf4e-49ea-933d-0077ddd7dc76,dea033e4-4173-4d3b-980c-d4c9b7a809b6,79a6f7f8-9555-476e-9ab7-2b571af71646,...,2022-03-20 18:06:42,2022-03-18 17:46:59,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,1b305001-84ed-4b3d-a9c6-9ab04da941ff
3086,2023-07-26 18:36:25.415124,2023-07-26 18:36:25.415124,False,NaT,ffc65a35-d493-48b9-90bb-5d519bbe657e,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,3bc34001-ec64-4793-9a54-f71a6bf3ce6e,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-09-22 18:26:24,2022-09-21 21:53:31,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
3087,2023-08-02 08:05:38.277226,2023-08-02 08:05:38.277226,False,NaT,ffc7d69e-c0f6-4162-ab9c-cb7fccb5afb5,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,2fd477dd-4fab-4965-95bd-3a708a6a899c,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-07-31 18:25:56,2023-07-30 00:00:00,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
3088,2023-07-26 18:36:29.142763,2023-07-26 18:36:29.142763,False,NaT,ffc88e39-d6d6-491c-94b1-6ecef9cc6104,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,c6dc1e49-5f86-4f40-8a96-0f81e561279a,dea033e4-4173-4d3b-980c-d4c9b7a809b6,28e85b78-fae7-4b70-983d-a0ad7d08f48c,...,2023-03-16 18:18:20,2023-03-14 20:34:41,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,8d58dea6-3556-492c-859f-f3b3827ab557
3089,2023-07-26 18:36:20.488998,2023-07-26 18:36:20.488998,False,NaT,ffe2ea50-058a-4231-ae05-fba34da1c125,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,7eec6e80-69b3-409a-ae38-d332def980b3,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-01-31 16:02:52,2022-01-28 19:09:47,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,f5bec75c-2c0a-450a-b11b-bfe412eabf23,OUTFLOW,None,1c615a8c-a254-4845-9d7d-964c42586d7f

In [4]:
# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM account_subtype"

# Load data into a pandas DataFrame
account_subtype = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [5]:
# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction_subtype"

# Load data into a pandas DataFrame
transaction_subtype = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [6]:
# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction_type"

# Load data into a pandas DataFrame
transaction_type = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [7]:
# Create a connection
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction_location"

# Load data into a pandas DataFrame
transaction_location = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [8]:
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction_category"

# Load data into a pandas DataFrame
transaction_category = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [9]:
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM transaction_category_association"

# Load data into a pandas DataFrame
transaction_category_association = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

# Print the DataFrame

In [10]:
conn = psycopg2.connect(**params)

# Define your query
sql_query = "SELECT * FROM financial_institution"

# Load data into a pandas DataFrame
financial_institution = pd.read_sql_query(sql_query, conn)

# Close the connection
conn.close()

In [11]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\pc\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\pc\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

WARNING: Ignoring invalid distribution -rotobuf (c:\users\pc\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\pc\anaconda3\lib\site-packages)

In [12]:

account.to_pickle('C:/Users/Pc/Documents/ipek_account_data/account.pkl')

In [21]:
transaction_subtype.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction_subtype.pkl')

In [20]:

account_subtype.to_pickle('C:/Users/Pc/Documents/ipek_account_data/account_subtype.pkl')

In [14]:

transaction_type.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction_type.pkl')

In [15]:

transaction_location.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction_location.pkl')

In [16]:

transaction_category.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction_category.pkl')

In [17]:

transaction_category_association.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction_category_association.pkl')

In [18]:

financial_institution.to_pickle('C:/Users/Pc/Documents/ipek_account_data/financial_institution.pkl')

In [19]:

transaction.to_pickle('C:/Users/Pc/Documents/ipek_account_data/transaction.pkl')

In [31]:
transactions

,created_at,updated_at,is_deleted,deleted_at,id,org_id,currency_id,vendor_id,source_id,location_id,...,datetime,authorized_datetime,is_pending,payment_channel,check_number,account_id,transaction_type_id,direction,general_ledger_account_id,transaction_subtype_id
0,2023-07-26 18:36:14.550089,2023-07-26 18:36:14.550089,False,NaT,0001378f-f744-4eb0-8b7b-867135071625,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,59475fb0-772f-4400-80f2-ac0100ee3921,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-07-16 16:51:11,2023-07-15 00:00:00,False,ONLINE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,0d8eb8f2-a462-4cce-98c5-2a2a681f80d4,OUTFLOW,None,dd56c6ee-b6d7-4f86-8620-80d7561b91af
1,2023-07-26 18:36:28.244705,2023-07-26 18:36:28.244705,False,NaT,0023ef80-81d0-4928-9a9e-22a85b810433,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,d53f2785-c3d9-45d3-be66-b3bc5316af37,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-01-30 16:58:42,2023-01-28 12:34:50,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
2,2023-07-26 18:36:20.091959,2023-07-26 18:36:20.091959,False,NaT,00241232-d353-4c0e-9a8e-6db7a4f42571,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,a17ca5fb-dc1f-4c17-9e59-53e7aa4873fd,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-01-30 14:31:30,2022-01-29 22:51:51,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,6e780bfb-9c0e-4b33-a8f2-8c8f6546213e,OUTFLOW,None,6ad0082b-e775-46d3-99bf-6f64c6eed332
3,2023-07-26 18:36:28.854304,2023-07-26 18:36:28.854304,False,NaT,003ec9a6-3078-48b5-a5ab-0b4dad9348bd,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,e0303369-24a3-49fe-b741-b9bfaefdcdab,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-02-21 17:58:43,2023-02-20 14:08:21,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,6e780bfb-9c0e-4b33-a8f2-8c8f6546213e,OUTFLOW,None,1691b033-2899-43b0-a3a3-680a9adec73f
4,2023-07-26 18:36:29.413804,2023-07-26 18:36:29.413804,False,NaT,00464921-516d-4e15-b236-b049b433bf46,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,342b827a-0607-4574-9249-41ecfda8de85,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-03-24 18:05:10,2023-03-23 14:05:39,False,ONLINE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,f5bec75c-2c0a-450a-b11b-bfe412eabf23,OUTFLOW,None,1c5b2213-d653-42cd-8086-e7db3c3ca432
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3085,2023-07-26 18:36:21.499517,2023-07-26 18:36:21.499517,False,NaT,ffac2fe0-3fd7-4dbc-abe1-e672d983a99e,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,c724db4c-cf4e-49ea-933d-0077ddd7dc76,dea033e4-4173-4d3b-980c-d4c9b7a809b6,79a6f7f8-9555-476e-9ab7-2b571af71646,...,2022-03-20 18:06:42,2022-03-18 17:46:59,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,1b305001-84ed-4b3d-a9c6-9ab04da941ff
3086,2023-07-26 18:36:25.415124,2023-07-26 18:36:25.415124,False,NaT,ffc65a35-d493-48b9-90bb-5d519bbe657e,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,3bc34001-ec64-4793-9a54-f71a6bf3ce6e,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-09-22 18:26:24,2022-09-21 21:53:31,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
3087,2023-08-02 08:05:38.277226,2023-08-02 08:05:38.277226,False,NaT,ffc7d69e-c0f6-4162-ab9c-cb7fccb5afb5,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,2fd477dd-4fab-4965-95bd-3a708a6a899c,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2023-07-31 18:25:56,2023-07-30 00:00:00,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,3783f38f-4027-4b86-a442-cea7666984c4
3088,2023-07-26 18:36:29.142763,2023-07-26 18:36:29.142763,False,NaT,ffc88e39-d6d6-491c-94b1-6ecef9cc6104,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,c6dc1e49-5f86-4f40-8a96-0f81e561279a,dea033e4-4173-4d3b-980c-d4c9b7a809b6,28e85b78-fae7-4b70-983d-a0ad7d08f48c,...,2023-03-16 18:18:20,2023-03-14 20:34:41,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,aea975b8-f29f-4052-a445-05b206e9b4f4,OUTFLOW,None,8d58dea6-3556-492c-859f-f3b3827ab557
3089,2023-07-26 18:36:20.488998,2023-07-26 18:36:20.488998,False,NaT,ffe2ea50-058a-4231-ae05-fba34da1c125,fe1a173a-76d6-4647-bb00-d615fb07f64c,USD,7eec6e80-69b3-409a-ae38-d332def980b3,dea033e4-4173-4d3b-980c-d4c9b7a809b6,None,...,2022-01-31 16:02:52,2022-01-28 19:09:47,False,IN_STORE,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,f5bec75c-2c0a-450a-b11b-bfe412eabf23,OUTFLOW,None,1c615a8c-a254-4845-9d7d-964c42586d7f

In [22]:
account

,created_at,updated_at,is_deleted,deleted_at,id,type,subtype_id,org_id,external_id,balance_available_amount,balance_current_amount,limit_amount,currency_id,account_number_mask,name,official_name,source_id,financial_institution_id,external_last_updated_datetime
0,2023-07-27 04:41:04.803048,2023-08-03 08:05:36.111597,False,None,1978c662-4cd4-4164-9d1e-0a938a89b43d,DEPOSIT,796ab970-42cb-4fe1-a913-7846c25335e6,c84e81e6-8663-427e-983e-95c9660da260,Z1889jN9oysoqKbw6Ookibo8gb04PMUxEQPyM,0.00,0.00,NaN,USD,6350,Mercury Savings,Mercury Savings,7e83b1fd-9a07-4044-8212-5d981c80fd06,97807784-6743-468d-b3ce-bb3d499ad903,2023-08-03 05:20:04.733
1,2023-07-27 04:39:57.678383,2023-08-03 08:05:41.316470,False,None,4c01f230-75ab-4cb8-b83d-8a9214795d40,DEPOSIT,796ab970-42cb-4fe1-a913-7846c25335e6,c84e81e6-8663-427e-983e-95c9660da260,BbODwjxjkLsB5Rw74MELhMnJkNYgE5igvX9Ej,500.57,500.57,NaN,USD,2435,BUSINESS MARKET RATE SAVINGS ...2435,BUSINESS MARKET RATE SAVINGS ...2435,5b97073d-cb13-40e8-a040-e87f30ace849,70d7f11e-d6a1-4b00-9391-3470d3690c12,2023-08-03 04:57:25.494
2,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,5332798b-523f-4d9a-9c7d-38f5aedfad60,DEPOSIT,e3f99647-fbe3-4176-bc3c-2cef55054c1c,fe1a173a-76d6-4647-bb00-d615fb07f64c,8mz6rb4YJnuydDRd4zNPhP1PjEZO0mUYO6dZP,3459.10,3459.10,NaN,USD,9836,TOTAL CHECKING,None,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
3,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,683eb2a6-4f9c-4a96-85e0-fa7bf9a7814e,CREDIT,854d29af-ef01-44d4-83a5-f1421d7eeeed,fe1a173a-76d6-4647-bb00-d615fb07f64c,5Zg7vx0YJNULNAgN0yq3S3D34NV7bwiN7pqVL,23500.93,55.24,23700.0,USD,5620,CREDIT CARD,Ultimate Rewards®,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
4,2023-07-27 04:39:57.678383,2023-08-03 08:05:41.316470,False,None,7d22926a-9632-4861-95a6-7aa2211963ae,DEPOSIT,7c4989df-3dd3-495e-a819-a414c4aebe15,c84e81e6-8663-427e-983e-95c9660da260,qNgLPprpqKuLmA15wX6dH1k8xDjOALUq1MJpx,8892.14,8892.14,NaN,USD,1567,BUSINESS CHECKING ...1567,BUSINESS CHECKING ...1567,5b97073d-cb13-40e8-a040-e87f30ace849,70d7f11e-d6a1-4b00-9391-3470d3690c12,2023-08-03 04:57:25.494
5,2023-08-03 11:12:14.317763,2023-08-03 11:12:14.317763,False,None,a283b87e-d112-4ec4-b61d-e9e9150c7fbc,DEPOSIT,97d09c89-eef8-4de0-baa3-9311f2c37859,fe1a173a-76d6-4647-bb00-d615fb07f64c,jZDJdE0qMXSE5Ev30e8osLAkd0Y08gtvee483,42847.82,42852.82,NaN,USD,3145,Savings Account,Savings Account,b6186ac8-7642-4c66-a3bb-0d9e05106b68,ccab6f08-1c16-487a-90c9-9715a722d03f,2023-08-03 11:11:56.354
6,2023-07-26 18:36:12.562229,2023-08-03 08:05:33.300269,False,None,a55c6d9f-4651-4e95-afce-7e597390a0b6,DEPOSIT,97d09c89-eef8-4de0-baa3-9311f2c37859,fe1a173a-76d6-4647-bb00-d615fb07f64c,ZZrdkBK6yQURA6jAvg37IX7XyjDVkMF8qZ0vq,1061.32,1061.32,NaN,USD,3150,CHASE SAVINGS,None,7965c146-d0d5-4cfb-a858-18c12cb90606,642a874e-a1c4-4256-b1b5-76b9fe407644,2023-08-02 20:59:12.899
7,2023-07-27 04:41:04.803048,2023-08-03 08:05:36.111597,False,None,d8a1ad91-a46d-4ba4-837c-9113962d08b9,DEPOSIT,7c4989df-3dd3-495e-a819-a414c4aebe15,c84e81e6-8663-427e-983e-95c9660da260,5waajMDjVJsZk9aBA1Z6ikn5akXmEwfKRLmE7,70000.00,70000.00,NaN,USD,5287,Mercury Checking,Mercury Checking,7e83b1fd-9a07-4044-8212-5d981c80fd06,97807784-6743-468d-b3ce-bb3d499ad903,2023-08-03 05:20:04.733